version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: update-dependencies
  ignore:
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.12.5
    - 7.13.10
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.15
    - 7.12.17
    - 7.13.10
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@types/cheerio"
    versions:
    - 0.22.23
    - 0.22.24
    - 0.22.25
    - 0.22.26
    - 0.22.27
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
