export enum NogizakaName {
  Nogizaka46 = '乃木坂46',
  AkimotoManatsu = '秋元真夏',
  IkutaErika = '生田絵梨花',
  InoueSayuri = '井上小百合',
  SaitouAsuka = '齋藤飛鳥',
  ShiraishiMai = '白石麻衣',
  TakayamaKazumi = '高山一実',
  NakadaKana = '中田花奈',
  HiguchiHina = '樋口日奈',
  HoshinoMinami = '星野みなみ',
  MatsumuraSayuri = '松村沙友理',
  WadaMaaya = '和田まあや',
  ItouJunna = '伊藤純奈',
  KitanoHinako = '北野日奈子',
  SasakiKotoko = '佐々木琴子',
  ShinuchiMai = '新内眞衣',
  SuzukiAyane = '鈴木絢音',
  TeradaRanze = '寺田蘭世',
  HoriMiona = '堀未央奈',
  YamazakiRena = '山崎怜奈',
  WatanabeMiria = '渡辺みり愛',
  ItouRiria = '伊藤理々杏',
  IwamotoRenka = '岩本蓮加',
  UmezakaMinami = '梅澤美波',
  OozonoMomoko = '大園桃子',
  KuboShiori = '久保史緒里',
  SakaguchiTamami = '阪口珠美',
  SatouKaede = '佐藤楓',
  NakamuraReno = '中村麗乃',
  MukaiHazuki = '向井葉月',
  YamashitaMizuki = '山下美月',
  YoshidaAyanoChristie = '吉田綾乃クリスティー',
  YodaYuuki = '与田祐希',
  EndouSakura = '遠藤さくら',
  KakiHaruka = '賀喜遥香',
  KakehashiSayaka = '掛橋沙耶香',
  KawagawaSaya = '金川紗耶',
  KitagawaYuri = '北川悠理',
  ShibataYuna = '柴田柚菜',
  SeimiyaRei = '清宮レイ',
  TamuraMayu = '田村真佑',
  TsutsuiAyame = '筒井あやめ',
  HayakawaSeira = '早川聖来',
  YakuboMio = '矢久保美緒',
  KuromiHaruka = '黒見明香',
  SatouRika = '佐藤璃果',
  HayashiRuna = '林瑠奈',
  MatsuoMiyu = '松尾美佑',
  YumikiNao = '弓木奈於',
  SakuraiReika = '桜井玲香',
  SaitouYuuri = '斉藤優里',
  ItouKarin = '伊藤かりん',
  EtouMisa = '衛藤美彩',
  KawagoHina = '川後陽菜',
  NishinoNanase = '西野七瀬',
  WakatsukiYumi = '若月佑美',
  NoujouAmi = '能條愛未',
  IkomaRina = '生駒里奈',
  KawamuraMahiro = '川村真洋',
  SaitouChiharu = '斎藤ちはる',
  SagaraIori = '相楽伊織',
  ItouMarika = '伊藤万理華',
  NakamotoHimeka = '中元日芽香',
  HashimotoNanami = '橋本奈々未',
  FukagawaMai = '深川麻衣',
  NagashimaSeira = '永島聖羅',
  MatsuiRena = '松井玲奈',
  HatanakaSeira = '畠中清羅',
  YamatoRina = '大和里菜',
  ItouNene = '伊藤寧々',
  IchikiRena = '市來玲奈',
  MiyazawaSeira = '宮沢セイラ',
  MiyazakaSeiraOld = '宮澤成良',
  KashiwaYukina = '柏幸奈',
  AndouMikumo = '安藤美雲',
  IwaseYumiko = '岩瀬佑美子',
}

export const NOGIZAKA_NAMES: NogizakaName[] = [
  NogizakaName.Nogizaka46,
  NogizakaName.AkimotoManatsu,
  NogizakaName.IkutaErika,
  NogizakaName.InoueSayuri,
  NogizakaName.SaitouAsuka,
  NogizakaName.ShiraishiMai,
  NogizakaName.TakayamaKazumi,
  NogizakaName.NakadaKana,
  NogizakaName.HiguchiHina,
  NogizakaName.HoshinoMinami,
  NogizakaName.MatsumuraSayuri,
  NogizakaName.WadaMaaya,
  NogizakaName.ItouJunna,
  NogizakaName.KitanoHinako,
  NogizakaName.SasakiKotoko,
  NogizakaName.ShinuchiMai,
  NogizakaName.SuzukiAyane,
  NogizakaName.TeradaRanze,
  NogizakaName.HoriMiona,
  NogizakaName.YamazakiRena,
  NogizakaName.WatanabeMiria,
  NogizakaName.ItouRiria,
  NogizakaName.IwamotoRenka,
  NogizakaName.UmezakaMinami,
  NogizakaName.OozonoMomoko,
  NogizakaName.KuboShiori,
  NogizakaName.SakaguchiTamami,
  NogizakaName.SatouKaede,
  NogizakaName.NakamuraReno,
  NogizakaName.MukaiHazuki,
  NogizakaName.YamashitaMizuki,
  NogizakaName.YoshidaAyanoChristie,
  NogizakaName.YodaYuuki,
  NogizakaName.EndouSakura,
  NogizakaName.KakiHaruka,
  NogizakaName.KakehashiSayaka,
  NogizakaName.KawagawaSaya,
  NogizakaName.KitagawaYuri,
  NogizakaName.ShibataYuna,
  NogizakaName.SeimiyaRei,
  NogizakaName.TamuraMayu,
  NogizakaName.TsutsuiAyame,
  NogizakaName.HayakawaSeira,
  NogizakaName.YakuboMio,
  NogizakaName.KuromiHaruka,
  NogizakaName.SatouRika,
  NogizakaName.HayashiRuna,
  NogizakaName.MatsuoMiyu,
  NogizakaName.YumikiNao,
  NogizakaName.SakuraiReika,
  NogizakaName.SaitouYuuri,
  NogizakaName.ItouKarin,
  NogizakaName.EtouMisa,
  NogizakaName.KawagoHina,
  NogizakaName.NishinoNanase,
  NogizakaName.WakatsukiYumi,
  NogizakaName.NoujouAmi,
  NogizakaName.IkomaRina,
  NogizakaName.KawamuraMahiro,
  NogizakaName.SaitouChiharu,
  NogizakaName.SagaraIori,
  NogizakaName.ItouMarika,
  NogizakaName.NakamotoHimeka,
  NogizakaName.HashimotoNanami,
  NogizakaName.FukagawaMai,
  NogizakaName.NagashimaSeira,
  NogizakaName.MatsuiRena,
  NogizakaName.HatanakaSeira,
  NogizakaName.YamatoRina,
  NogizakaName.ItouNene,
  NogizakaName.IchikiRena,
  NogizakaName.MiyazawaSeira,
  NogizakaName.MiyazakaSeiraOld,
  NogizakaName.KashiwaYukina,
  NogizakaName.AndouMikumo,
  NogizakaName.IwaseYumiko,
];
