export enum NogizakaScheduleType {
  Live = 'live',
  Handshake = 'handshake',
  Tv = 'tv',
  Radio = 'radio',
  Magazine = 'magazine',
  Web = 'web',
  Movie = 'movie',
  Theatre = 'theatre',
  Release = 'release',
  Birthday = 'birthday',
}

export enum NogizakaScheduleTypeName {
  Live = 'LIVE/EVENT',
  Handshake = '握手会',
  Tv = 'TV',
  Radio = 'RADIO',
  Magazine = 'MAGAZINE',
  Web = 'WEB',
  Movie = 'MOVIE',
  Theatre = 'THEATRE',
  Release = 'RELEASE',
  Birthday = '誕生日',
}

export const NOGIZAKA_SCHEDULE_TYPES: {
  type: NogizakaScheduleType;
  className: string;
  displayName: NogizakaScheduleTypeName;
}[] = [
  {
    type: NogizakaScheduleType.Live,
    className: '.live',
    displayName: NogizakaScheduleTypeName.Live,
  },
  {
    type: NogizakaScheduleType.Handshake,
    className: '.handshake',
    displayName: NogizakaScheduleTypeName.Handshake,
  },
  {
    type: NogizakaScheduleType.Tv,
    className: '.tv',
    displayName: NogizakaScheduleTypeName.Tv,
  },
  {
    type: NogizakaScheduleType.Radio,
    className: '.radio',
    displayName: NogizakaScheduleTypeName.Radio,
  },
  {
    type: NogizakaScheduleType.Magazine,
    className: '.magazine',
    displayName: NogizakaScheduleTypeName.Magazine,
  },
  {
    type: NogizakaScheduleType.Web,
    className: '.web',
    displayName: NogizakaScheduleTypeName.Web,
  },
  {
    type: NogizakaScheduleType.Movie,
    className: '.movie',
    displayName: NogizakaScheduleTypeName.Movie,
  },
  {
    type: NogizakaScheduleType.Theatre,
    className: '.theatre',
    displayName: NogizakaScheduleTypeName.Theatre,
  },
  {
    type: NogizakaScheduleType.Release,
    className: '.release',
    displayName: NogizakaScheduleTypeName.Release,
  },
  {
    type: NogizakaScheduleType.Birthday,
    className: '.bd',
    displayName: NogizakaScheduleTypeName.Birthday,
  },
];

export const LLC_SCHEDULE_TYPE_LIST = ['TV', 'RADIO', 'MAGAZINE', 'WEB', 'STAGE', 'EVENT', 'RELEASE', 'LIVE', 'OTHER'];

export const HOURS = {
  jp: [
    '0時',
    '1時',
    '2時',
    '3時',
    '4時',
    '5時',
    '6時',
    '7時',
    '8時',
    '9時',
    '10時',
    '11時',
    '12時',
    '13時',
    '14時',
    '15時',
    '16時',
    '17時',
    '18時',
    '19時',
    '20時',
    '21時',
    '22時',
    '23時',
    '24時',
    '25時',
    '26時',
    '27時',
  ],
  normal: [
    '0:',
    '1:',
    '2:',
    '3:',
    '4:',
    '5:',
    '6:',
    '7:',
    '8:',
    '9:',
    '10:',
    '11:',
    '12:',
    '13:',
    '14:',
    '15:',
    '16:',
    '17:',
    '18:',
    '19:',
    '20:',
    '21:',
    '22:',
    '23:',
    '24:',
    '25:',
    '26:',
    '27:',
  ],
  twoByte: [
    '0：',
    '1：',
    '2：',
    '3：',
    '4：',
    '5：',
    '6：',
    '7：',
    '8：',
    '9：',
    '10：',
    '11：',
    '12：',
    '13：',
    '14：',
    '15：',
    '16：',
    '17：',
    '18：',
    '19：',
    '20：',
    '21：',
    '22：',
    '23：',
    '24：',
    '25：',
    '26：',
    '27：',
  ],
};
