name: Build CI

on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Format
        run: yarn format
      - name: Type check
        run: yarn type-check
      - name: Lint
        run: yarn lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Commit to bundle
        uses: EndBug/add-and-commit@v4
        with:
          add: 'dist'
          message: 'Update bundled files'
          ref: bundle
          force: true
